version: "3.8"

# environment
x-env-db: &db-env
  POSTGRES_DB: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_USER: "root"

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nayanbiswas/fastapi_bp_server:latest
    container_name: fastapi_bp_server
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - ./:/code
    depends_on:
      - db
      - redis
    networks:
      - fastapi_bp_tier

  worker:
    image: nayanbiswas/fastapi_bp_server:latest
    container_name: fastapi_bp_worker
    restart: unless-stopped
    command:
      "watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- \
      celery --app=worker.main:celery_app worker --beat --loglevel=debug"
    env_file: .env
    volumes:
      - ./:/code
    depends_on:
      - db
      - redis
    networks:
      - fastapi_bp_tier

  db:
    image: postgres:16
    container_name: fastapi_bp_db
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      <<: *db-env
    networks:
      - fastapi_bp_tier
    volumes:
      - fastapi_bp_db:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fastapi_bp_redis
    restart: unless-stopped
    networks:
      - fastapi_bp_tier
    volumes:
      - fastapi_bp_redis:/data

volumes:
  fastapi_bp_db:
    driver: local
  fastapi_bp_redis:
    driver: local

networks:
  fastapi_bp_tier:
    driver: bridge
